name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push client image
      uses: docker/build-push-action@v5
      with:
        context: . # Location of the Dockerfile relative to the root of the repository
        file: ./Dockerfile.client
        target: final
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            dandychux/rusty-melody-client:latest
        build-args: |
            SERVER_URL=${{ secrets.SERVER_URL }}
            CLIENT_URL=${{ secrets.CLIENT_URL }}

    - name: Build and push server image
      uses: docker/build-push-action@v5
      with:
        context: . # Location of the Dockerfile relative to the root of the repository
        file: ./Dockerfile.server
        target: final
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            dandychux/rusty-melody-server:latest
        build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            JWT_EXPIRED_IN=${{ secrets.JWT_EXPIRED_IN }}
            JWT_MAXAGE=${{ secrets.JWT_MAXAGE }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}

